### PR TITLE
Looking to revive this project

### PR DESCRIPTION
**Pull request by nwithan8**
Hoping to eventually map out the Jellyfin API entirely for a Python library

### CODE REVIEW

**Comment by tiedtoastar** [comment]
Good start!

There is one thing I noticed. Did you mean to use /Items/RemoteSearch for all your searches?
I don't believe RemoteSearch searches the servers library, rather it search a remote database such as musicbrainz.

**Comment by nwithan8** [comment]
Oh, didn't know that. What should I use instead?

**Comment by tiedtoastar** [comment]
/Users/{UserId}/Items

I'd look at the emby documentation, I don't see the documentation for jellyfin out at jellyfin.org/docs

https://github.com/MediaBrowser/Emby/wiki/Browsing-the-Library

Also recommend adding unit tests to your search functions.

**Comment by nwithan8** [comment]
Yep, just discovered that about an hour ago. The API as a whole seems
really fractured right now, but thanks for doing your best to work with it.

**Pull request merged**
